# Generated by Django 4.2.29 on 2026-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nginxnode',
            name='ssh_key_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SSH私钥路径'),
        ),
        migrations.AddField(
            model_name='nginxnode',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SSH密码'),
        ),
        migrations.AddField(
            model_name='nginxnode',
            name='ssh_port',
            field=models.IntegerField(default=22, verbose_name='SSH端口'),
        ),
        migrations.AddField(
            model_name='nginxnode',
            name='ssh_username',
            field=models.CharField(default='root', max_length=100, verbose_name='SSH用户名'),
        ),
        migrations.AlterField(
            model_name='ipblockrule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nginxconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nginxnode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ratelimitrule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='routerule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
